java_home: unknown
hbase_version: unknown
hbase_local_tar: unknown

hbase_user: hbase
hbase_group: hbase
hbase_target_dir: /opt/hbase
hbase_distro_home: "{{ hbase_target_dir }}/current"


# 是否删除已有的target_dir
delete_target_dir: false
# 是否重新部署配置项
reconfig: false


hbase_data_dir: "{{ hbase_distro_home }}/data"
hbase_log_dir: "{{ hbase_distro_home }}/logs"
hbase_workders: 
  localhost: 1

hbase_site: {}
hbase_site_defaults:
  hbase.cluster.distributed: false
  hbase.rootdir: /tmp/hbase
  dfs.replication: 1
  hbase.master.port: 16000
  hbase.zookeeper.quorum: localhost
  hbase.zookeeper.property.dataDir: /var/zookeeper

