---
- name: "Unarchive kafka tgz to '{{ kafka_target_dir }}'"
  ansible.builtin.unarchive:
    src: "{{ kafka_local_tar }}"
    dest: "{{ kafka_target_dir }}"
    list_files: yes
    creates: "{{ kafka_target_dir }}/kafka_2.12-{{ kafka_version }}/bin/kafka-cluster.sh"
  register: unarchive_res


- name: Debug | Show unarchive result
  debug:
    msg: "unarchive_res.failed: {{ unarchive_res.failed }}, unarchive_res.changed: {{ unarchive_res.changed }}"

- name: Debug | show kafka unarchive_res
  ansible.builtin.debug:
    var: unarchive_res.files[0]

# 找出解压后的父级文件夹名称
# - name: Debug | Show kafka archive dir
#   ansible.builtin.debug:
#     msg: "{{ kafka_target_dir }}/{{ unarchive_res.files[0] | regex_replace('/+$', '') }}"
# 使用下面这个方式更加健壮
- name: Debug | Show kafka archive dir
  ansible.builtin.debug:
    msg: "{{ kafka_target_dir }}/{{ unarchive_res.files[0].split('/')[0] }}"


- name: "Create link from {{ kafka_target_dir }}/{{ unarchive_res.files[0].split('/')[0] }} to current kafka distro {{ kafka_distro_home }}."
  ansible.builtin.file:
    path: "{{ kafka_distro_home }}"
    src: "{{ kafka_target_dir }}/{{ unarchive_res.files[0].split('/')[0] }}"
    state: link
  when: unarchive_res.changed

# 修改链接文件夹的权限/user/group，会直接修改目标文件夹的属性
- name: "Change owner to {{ kafka_user }} and allow group {{ kafka_group }} rwx"
  ansible.builtin.file:
    path: "{{ kafka_distro_home }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: u=rwx,g=rwx,o=r
    recurse: yes
    state: directory

