---
- name: "Unarchive hive tgz to '{{ hive_target_dir }}'"
  ansible.builtin.unarchive:
    src: "{{ hive_local_tar }}"
    dest: "{{ hive_target_dir }}"
    list_files: yes
    creates: "{{ hive_target_dir }}/apache-hive-{{ hive_version }}-bin/bin/zkServer.sh"
  register: unarchive_res


- name: Debug | Show unarchive result
  debug:
    msg: "unarchive_res.failed: {{ unarchive_res.failed }}, unarchive_res.changed: {{ unarchive_res.changed }}"

- name: Debug | Show hive unarchive_res
  ansible.builtin.debug:
    var: unarchive_res.files[0]

- name: Debug | Show hive archive dir
  ansible.builtin.debug:
    msg: "{{ hive_target_dir }}/{{ unarchive_res.files[0].split('/')[0] }}"


- name: "Create link from {{ hive_target_dir }}/{{ unarchive_res.files[0].split('/')[0] }} to current hive distro {{ hive_distro_home }}."
  ansible.builtin.file:
    path: "{{ hive_distro_home }}"
    src: "{{ hive_target_dir }}/{{ unarchive_res.files[0].split('/')[0] }}"
    state: link
  when: unarchive_res.changed

# 修改链接文件夹的权限/user/group，会直接修改目标文件夹的属性
- name: "Change owner to {{ hive_user }} and allow group {{ hive_group }} rwx"
  ansible.builtin.file:
    path: "{{ hive_distro_home }}"
    owner: "{{ hive_user }}"
    group: "{{ hive_group }}"
    mode: u=rwx,g=rwx,o=r
    recurse: yes
    state: directory


