---
# - name: Stop hive server
#   shell: "{{ hive_distro_home }}/bin/zkServer.sh stop"
#   environment:
#     JAVA_HOME: "{{ java_home }}"
#   become: yes
#   become_user: "{{ hive_user }}"
#   ignore_errors: true
